title: Kevin Bates
logo: /images/circle2.jpg
description: Data-driven strategist turning insights into impact through analytics, storytelling, and smart execution
show_downloads: true
theme: jekyll-theme-slate
